package com.aistar.mapper;

import com.aistar.pojo.Job;
import com.aistar.pojo.JobExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;
@Repository
public interface JobMapper {

    public List<Job> selectAllJobBySearch(@Param("kw") String kw,
                                          @Param("city") String city,
                                          @Param("publishTime") Date publishTime,
                                          @Param("minSalary") Float minSalary,
                                          @Param("maxSalary") Float maxSalary,
                                          @Param("workYear") String workYear,
                                          @Param("degree") String degree,
                                          @Param("company") String company
    );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Thu Feb 13 09:39:31 CST 2020
     */
    int countByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Thu Feb 13 09:39:31 CST 2020
     */
    int deleteByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Thu Feb 13 09:39:31 CST 2020
     */
    int deleteByPrimaryKey(Integer jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Thu Feb 13 09:39:31 CST 2020
     */
    int insert(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Thu Feb 13 09:39:31 CST 2020
     */
    int insertSelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Thu Feb 13 09:39:31 CST 2020
     */
    List<Job> selectByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Thu Feb 13 09:39:31 CST 2020
     */
    Job selectByPrimaryKey(Integer jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Thu Feb 13 09:39:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") Job record, @Param("example") JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Thu Feb 13 09:39:31 CST 2020
     */
    int updateByExample(@Param("record") Job record, @Param("example") JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Thu Feb 13 09:39:31 CST 2020
     */
    int updateByPrimaryKeySelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Thu Feb 13 09:39:31 CST 2020
     */
    int updateByPrimaryKey(Job record);
}