package com.aistar.mapper;

import com.aistar.pojo.Skill;
import com.aistar.pojo.SkillExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface SkillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Feb 13 09:39:32 CST 2020
     */
    int countByExample(SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Feb 13 09:39:32 CST 2020
     */
    int deleteByExample(SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Feb 13 09:39:32 CST 2020
     */
    int deleteByPrimaryKey(Integer skillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Feb 13 09:39:32 CST 2020
     */
    int insert(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Feb 13 09:39:32 CST 2020
     */
    int insertSelective(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Feb 13 09:39:32 CST 2020
     */
    List<Skill> selectByExample(SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Feb 13 09:39:32 CST 2020
     */
    Skill selectByPrimaryKey(Integer skillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Feb 13 09:39:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") Skill record, @Param("example") SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Feb 13 09:39:32 CST 2020
     */
    int updateByExample(@Param("record") Skill record, @Param("example") SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Feb 13 09:39:32 CST 2020
     */
    int updateByPrimaryKeySelective(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Feb 13 09:39:32 CST 2020
     */
    int updateByPrimaryKey(Skill record);
}